sudo: false

language: python

python:
  - 3.5
  - 3.8

env:
  - TOX_ENV=django30
  - TOX_ENV=django22

matrix:
  exclude:
    - python: 3.5
      env: TOX_ENV=django30

before_install:
  - pip install pip==20.0.2

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
